name: Build my_veeam_report_to_xlsx

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            PYTHON_VER: 3.8
            CMD_BUILD: pyinstaller -F my_veeam_report_to_xlsx/my_veeam_report_to_xlsx.spec
            OUT_FILE_NAME: my_veeam_report_to_xlsx.exe
            SAVE_AS_NAME: my_veeam_report_to_xlsx.exe
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - name: Set up Python ${{matrix.PYTHON_VER}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.PYTHON_VER}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r my_veeam_report_to_xlsx/requirements.txt
    - name: Build with pyinstaller for ${{matrix.os}}
      run: ${{matrix.CMD_BUILD}}
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.SAVE_AS_NAME}}
        path: ./dist/${{matrix.OUT_FILE_NAME}}
        retention-days: 7
